const fs = require('fs');
const path = require('path');
const DiffService = require('./diffService');
const GitStatusParser = require('./gitStatusParser');
const GitService = require('./GitService');

class ReviewGenerator {
  /**
   * Generate split review files
   * @param {Object} options
   * @param {Array} options.includedFiles - List of files to process
   * @param {Object} options.comments - File-level comments
   * @param {Object} options.lineComments - Line-level comments
   * @param {string} options.outputDir - Output directory (optional, default: timestamped)
   * @returns {Promise<Object>} Result stats
   */
  static async generateSplitReviews({ includedFiles, comments = {}, lineComments = {}, outputDir = null }) {
    // Determine output directory
    let reviewDir;
    if (outputDir) {
      reviewDir = outputDir;
    } else {
      const timestamp = new Date().toISOString().slice(0, 19).replace(/[:]/g, '-');
      reviewDir = `code-reviews-${timestamp}`;
    }

    const reviewPath = path.resolve(process.cwd(), reviewDir);

    // Create directory
    try {
      if (!fs.existsSync(reviewPath)) {
        fs.mkdirSync(reviewPath, { recursive: true });
      }
    } catch (error) {
      throw new Error(`Failed to create review directory: ${error.message}`);
    }

    let filesCreated = 0;
    const errors = [];
    const createdFiles = [];

    // Generate Summary Content
    let summaryContent = `# 🔍 Code Review Summary\n\n`;
    summaryContent += `**Generated:** ${new Date().toLocaleString()}\n`;
    summaryContent += `**Total Files:** ${includedFiles.length}\n\n`;
    summaryContent += `## 📂 Review Files\n`;

    for (const file of includedFiles) {
      try {
        const safeName = file.replace(/[^a-zA-Z0-9.\-_]/g, '_');
        const reviewFileName = `review-${safeName}.md`;
        const reviewFilePath = path.join(reviewPath, reviewFileName);

        const content = await this.generateFileContent(file, comments[file], lineComments);

        fs.writeFileSync(reviewFilePath, content, 'utf8');
        filesCreated++;
        createdFiles.push(reviewFileName);

        summaryContent += `- [${file}](./${reviewFileName})\n`;

      } catch (error) {
        console.error(`❌ Error creating review for ${file}:`, error);
        errors.push(file);
        summaryContent += `- ❌ ${file} (Error: ${error.message})\n`;
      }
    }

    // Write Summary
    fs.writeFileSync(path.join(reviewPath, '00_SUMMARY.md'), summaryContent, 'utf8');

    return {
      success: true,
      directory: reviewDir,
      absolutePath: reviewPath,
      filesCreated,
      totalFiles: includedFiles.length,
      errors
    };
  }

  /**
   * Generate unified review file (AI_REVIEW.md)
   * @param {Object} options
   * @param {Array} options.includedFiles - List of files to process
   * @param {Array} options.excludedFiles - List of excluded files
   * @param {Array} options.largeFiles - List of skipped large files
   * @returns {Promise<Object>} Result stats and content
   */
  static async generateUnifiedReview({ includedFiles, excludedFiles = [], largeFiles = [] }) {
    const timestamp = new Date().toLocaleString();
    let content = `# 🔍 Code Review - ${timestamp}\n\n`;
    content += `**Project:** AI Visual Code Review\n`;
    content += `**Generated by:** AI Visual Code Review v2.0\n\n`;

    // Change Summary
    try {
      const stats = await GitService.getDiffStats();
      content += `## 📊 Change Summary\n\n\`\`\`\n${stats.trim()}\n\`\`\`\n\n`;
    } catch (err) {
      content += `## 📊 Change Summary\n\n(Stats not available)\n\n`;
    }

    content += `## 📝 Files Changed (${includedFiles.length} selected)\n\n`;

    if (excludedFiles.length > 0) {
      content += `### ⏭️ Excluded Files\nThe following files were excluded from this review:\n${excludedFiles.map(f => `- \`${f}\``).join('\n')}\n\n`;
    }

    if (largeFiles.length > 0) {
      content += `### 📦 Large Files Skipped\nThe following files were skipped due to size (use --no-size-limit to include):\n${largeFiles.map(f => `- \`${f}\``).join('\n')}\n\n`;
    }

    let processedCount = 0;
    const errors = [];

    // Get file statuses once
    let fileStatuses = {};
    try {
      fileStatuses = await GitService.getFileStatuses();
    } catch (error) {
      // console.warn('Failed to get file statuses:', error);
    }

    // Process each included file
    for (const file of includedFiles) {
      try {
        console.log(`✅ Processing: ${file}`);

        // Get file status
        let fileStatus = fileStatuses[file] || 'M ';

        const statusInfo = GitStatusParser.parse(fileStatus);
        content += `\n${GitStatusParser.getMarkdownHeader(fileStatus, file)}\n\n`;

        const statusMessage = GitStatusParser.getStatusMessage(fileStatus);
        if (statusMessage) {
          content += `${statusMessage}\n\n`;
        }

        if (!statusInfo.isDeleted) {
          const ext = path.extname(file).toLowerCase();
          const fileTypeMap = {
            '.tsx': '**Type:** TypeScript React Component ⚛️\n\n',
            '.ts': '**Type:** TypeScript Source File 📘\n\n',
            '.js': '**Type:** JavaScript Source File 🟨\n\n',
            '.jsx': '**Type:** React Component (JavaScript) ⚛️\n\n',
            '.json': '**Type:** Configuration/Data File 📋\n\n',
            '.md': '**Type:** Documentation 📖\n\n',
            '.css': '**Type:** Stylesheet 🎨\n\n',
            '.scss': '**Type:** Sass Stylesheet 🎨\n\n',
            '.html': '**Type:** HTML Template 🌐\n\n',
            '.py': '**Type:** Python Script 🐍\n\n',
            '.sh': '**Type:** Shell Script 💻\n\n',
            '.vue': '**Type:** Vue Component 💚\n\n',
            '.yaml': '**Type:** YAML Configuration 📋\n\n',
            '.yml': '**Type:** YAML Configuration 📋\n\n',
            '.toml': '**Type:** TOML Configuration 📋\n\n'
          };
          content += fileTypeMap[ext] || '**Type:** Source File 📄\n\n';
        }

        // Get diff
        let diff;
        try {
          diff = await GitService.getDiffForFile(file);
          if (!diff || diff.trim().length === 0) {
            if (statusInfo.isDeleted) {
              processedCount++;
              continue;
            }
            throw new Error('No diff content');
          } else {
            content += DiffService.generateEnhancedDiffMarkdown(diff);
          }
        } catch (diffError) {
          if (statusInfo.isDeleted) {
            processedCount++;
            continue;
          }
          throw diffError;
        }

        processedCount++;

      } catch (error) {
        console.error(`❌ Error processing ${file}:`, error.message);
        errors.push(file);
        content += `**❌ Error:** Could not load diff for \`${file}\` - ${error.message}\n\n`;
      }
    }

    content += this.getChecklistTemplate().replace("# 🔍 Code Review", "").replace("## 📊 File Information", ""); // Remove duplicate headers from checklist template if reusing

    // Write to file
    const filePath = path.join(process.cwd(), 'AI_REVIEW.md');
    fs.writeFileSync(filePath, content, 'utf8');

    return {
      success: true,
      file: 'AI_REVIEW.md',
      contentLength: content.length,
      filesProcessed: processedCount,
      errors
    };
  }

  /**
   * Generate content for a single file review
   */
  static async generateFileContent(file, fileComment, lineComments) {
    const ext = path.extname(file).toLowerCase();
    const fileTypeMap = {
      '.tsx': 'TypeScript React Component ⚛️',
      '.ts': 'TypeScript Source File 📘',
      '.js': 'JavaScript Source File 🟨',
      '.jsx': 'React Component (JavaScript) ⚛️',
      '.json': 'Configuration/Data File 📋',
      '.md': 'Documentation 📖',
      '.css': 'Stylesheet 🎨',
      '.scss': 'Sass Stylesheet 🎨',
      '.html': 'HTML Template 🌐',
      '.py': 'Python Script 🐍',
      '.sh': 'Shell Script 💻'
    };

    let content = `# 📄 Code Review: \`${file}\`\n\n`;
    content += `**Generated:** ${new Date().toLocaleString()}\n`;
    content += `**Project:** AI Visual Code Review\n`;
    content += `**Review Type:** Individual File Analysis\n\n`;

    content += `## 📊 File Information\n\n`;
    content += `**Type:** ${fileTypeMap[ext] || 'Source File 📄'}\n`;
    content += `**Path:** \`${file}\`\n`;
    content += `**Extension:** ${ext || 'None'}\n\n`;

    // File Comment
    if (fileComment) {
      content += `## 💭 Review Comment\n\n${fileComment}\n\n`;
    }

    // Line Comments
    const fileLineComments = Object.entries(lineComments || {})
      .filter(([lineId]) => lineId.includes(file.replace(/[^a-zA-Z0-9]/g, '_')));

    if (fileLineComments.length > 0) {
      content += `## 🔍 Line Comments\n\n`;
      fileLineComments.forEach(([lineId, comment]) => {
        content += `- **${lineId}:** ${comment}\n`;
      });
      content += '\n';
    }

    // Diff
    try {
      const diff = await GitService.getDiffForFile(file);
      content += `## 📝 Changes\n\n`;
      content += DiffService.generateEnhancedDiffMarkdown(diff);
    } catch (error) {
      content += `## ❌ Error\n\nCould not load diff for \`${file}\`: ${error.message}\n\n`;
    }

    // Checklist
    content += this.getChecklistTemplate();

    return content;
  }

  static getChecklistTemplate() {
    return `## 🤖 Comprehensive Review Checklist

### ✅ Code Quality & Standards
- [ ] **Syntax & Formatting**: Consistent indentation, proper spacing
- [ ] **Naming Conventions**: Clear, descriptive variable/function names
- [ ] **Code Structure**: Logical organization, appropriate function size
- [ ] **Documentation**: Clear comments explaining complex logic
- [ ] **Type Safety**: Proper typing (if applicable)

### 🔍 Logic & Functionality
- [ ] **Algorithm Correctness**: Logic implements requirements correctly
- [ ] **Edge Case Handling**: Boundary conditions properly addressed
- [ ] **Error Handling**: Appropriate try-catch blocks and error messages
- [ ] **Performance**: Efficient algorithms, no unnecessary loops
- [ ] **Memory Management**: Proper cleanup, no memory leaks

### 🐛 Potential Issues & Bugs
- [ ] **Runtime Errors**: No null/undefined dereferencing
- [ ] **Type Mismatches**: Consistent data types throughout
- [ ] **Race Conditions**: Proper async/await handling
- [ ] **Resource Leaks**: Event listeners, timers properly cleaned up
- [ ] **Off-by-one Errors**: Array/loop bounds correctly handled

### 🔒 Security Considerations
- [ ] **Input Validation**: User inputs properly sanitized
- [ ] **XSS Prevention**: No unsafe HTML injection
- [ ] **Authentication**: Proper access controls if applicable
- [ ] **Data Exposure**: No sensitive information in logs/client
- [ ] **Dependency Security**: No known vulnerable packages

### 📱 User Experience & Accessibility
- [ ] **Responsive Design**: Works on different screen sizes
- [ ] **Loading States**: Proper feedback during operations
- [ ] **Error Messages**: User-friendly error communication
- [ ] **Accessibility**: ARIA labels, keyboard navigation
- [ ] **Performance**: Fast loading, smooth interactions

### 💡 Improvement Suggestions

#### Code Organization
- [ ] Consider extracting complex logic into separate functions
- [ ] Evaluate if constants should be moved to configuration
- [ ] Check for code duplication opportunities

#### Performance Optimizations
- [ ] Identify opportunities for memoization
- [ ] Consider lazy loading for heavy operations
- [ ] Evaluate database query efficiency (if applicable)

#### Testing Recommendations
- [ ] Unit tests for core functionality
- [ ] Integration tests for API endpoints
- [ ] Edge case testing scenarios

#### Documentation Needs
- [ ] API documentation updates
- [ ] Code comments for complex algorithms
- [ ] README updates if public interfaces changed

### 📝 Review Notes
*Add your specific feedback, suggestions, and observations here:*

---
*Individual file review generated by AI Visual Code Review v2.0*
*Generated: ${new Date().toISOString()}*
`;
  }
}

module.exports = ReviewGenerator;
